### ISSUE TITLE
not supported 的意思是不支持检测还是正在检测中？

### ISSUE THREAD

**Issue by NickYan7** [Maskhe/FastjsonScan#1]
很赞的项目，前排膜拜大佬~

试了好几个站，都输出 not supported，是正在检测呢还是都不支持检测啊- -  （逃

**Comment by Maskhe** [comment]
> 很赞的项目，前排膜拜大佬~
> 
> 试了好几个站，都输出 not supported，是正在检测呢还是都不支持检测啊- - （逃

不支持的格式...(不好意思，忘回复了😂)
