### ISSUE TITLE
扫描跳过策略建议

### ISSUE THREAD

**Issue by LandGrey** [Maskhe/FastjsonScan#2]
看到有段代码 `如果使用者将非post类型或者非json数据的请求发送到fastjson scan中，则会直接提示not supporeted`。

建议对于 POST 请求，如果 `Content-Type` 类型不是类似于 `application/json` 的 json 数据，可以强制改成 `application/json` 后再主动探测。

**Comment by Maskhe** [comment]
> 看到有段代码 `如果使用者将非post类型或者非json数据的请求发送到fastjson scan中，则会直接提示not supporeted`。
> 
> 建议对于 POST 请求，如果 `Content-Type` 类型不是类似于 `application/json` 的 json 数据，可以强制改成 `application/json` 后再主动探测。

收到，空了更新下

**Comment by LandGrey** [comment]
> > 看到有段代码 `如果使用者将非post类型或者非json数据的请求发送到fastjson scan中，则会直接提示not supporeted`。
> > 建议对于 POST 请求，如果 `Content-Type` 类型不是类似于 `application/json` 的 json 数据，可以强制改成 `application/json` 后再主动探测。
> 
> 收到，空了更新下

nice
